[package]
name = "fugu"
version = "0.1.0"
edition = "2024"

[dependencies]
assert_cmd = "2"
fugu-core = { path = "../crates/fugu-core" }
tree-printer = { path = "../crates/tree-printer" }
clap = { version = "4.6.5", features = ["derive"] }

[dev-dependencies]
rstest = { workspace = true }
tempfile = { workspace = true }